### ISSUE TITLE
crash running fakexrandr-manage, segfault running xrandr after install

### ISSUE THREAD

**Issue by lope** [phillipberndt/fakexrandr#13]
```
$ make
cc -O2 -fPIC -shared -o libXrandr.so libXrandr.c
[ -e libXrandr.so.2 ] || ln -s libXrandr.so libXrandr.so.2
[ -e libXinerama.so.1 ] || ln -s libXrandr.so libXinerama.so.1

$ sudo make install
TARGET_DIR=`sed -nre 's/#define FAKEXRANDR_INSTALL_DIR "([^"]+)"/\1/p' config.h`; \
	echo $TARGET_DIR; \
	[ -d $TARGET_DIR ] || exit 1; \
	install libXrandr.so $TARGET_DIR; \
	ln -s libXrandr.so $TARGET_DIR/libXrandr.so.2 || true; \
	ln -s libXrandr.so $TARGET_DIR/libXinerama.so.1 || true; \
	ldconfig
/usr/local/lib
install fakexrandr-manage.py /usr/bin/fakexrandr-manage

/tmp/fakexrandr $ fakexrandr-manage
Traceback (most recent call last):
  File "/usr/bin/fakexrandr-manage", line 708, in <module>
    perform_action(action)
  File "/usr/bin/fakexrandr-manage", line 627, in perform_action
    wnd = MainWindow()
  File "/usr/bin/fakexrandr-manage", line 605, in __init__
    self.load_displays()
  File "/usr/bin/fakexrandr-manage", line 500, in load_displays
    self._displays = query_xrandr()
  File "/usr/bin/fakexrandr-manage", line 152, in query_xrandr
    outputs[out.contents.name]["crtc"] = crtcs[outputs[out.contents.name]["crtc"]]
KeyError: 0L

```

I'm running linux mint 17, based on Ubuntu 14.04.
Running a DisplayPort adapter with 2x 1920x1080 outputs joined into 3840x1080
http://www.sunix.com.tw/product/dpd2000.html

**Comment by lope** [comment]
Thanks.
What is the method to overwrite an old fakexrandr installation with a new one?

**Comment by phillipberndt** [comment]
And thank you for the bug report! The two commits should fix both bugs. (Note: They are in a bug13 branch currently, not in master.)

You don't have to do anything special, `make && make install` should overwrite the old installation.

**Comment by lope** [comment]
Awesome :) the fakexrandr manage GUI is running. Busy figuring out the controls etc.

**Comment by phillipberndt** [comment]
Great. Does xrandr work as expected, too?

**Comment by lope** [comment]
xrandr is working thanks, going to open another issue regarding fakexrandr-manage usage.
