### ISSUE TITLE
Issue when Running fakexrandr-manage - RPI B3+

### ISSUE THREAD

**Issue by Bobet21** [phillipberndt/fakexrandr#52]
Hey,

I face the following issue - ctypes library does exist in my python 2.7 libraries - i also tried to exchange logical as reccomended in #28 but still the error remains the same. The only thing i could see is that it looks for /usr/lib/libX11.so while this beeing contained in my /usr/lib/arm-linux-gnueabihf

I am running on RPI strectch Desktop

>  /usr/bin/fakexrandr-manage:37: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk
The GUI requires ctypes to be able to open libX11.so and an X Display

And from the python console i get

> fakexrandr-manage.py:37: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk
The GUI requires ctypes to be able to open libX11.so and an X Display
Traceback (most recent call last):
  File "/home/pi/fakexrandr/fakexrandr-manage.py", line 732, in <module>
    perform_action(action)
  File "/home/pi/fakexrandr/fakexrandr-manage.py", line 642, in perform_action
    require_x11()
  File "/home/pi/fakexrandr/fakexrandr-manage.py", line 78, in require_x11
    sys.exit(1)
SystemExit: 1

Seems that the HAS_X11_DISPLAY=FALSE I am not sure how i could help this...

Keeping on documenting my issue :+1: 

Adding "/usr/lib/arm-Linux-gneueabihf" in the list of repository (line 53 of fakexrandr-manage.py) and reinstalling allows me to open the GUI - but i don't see any available display - which really is not helping ...

**Comment by Bobet21** [comment]
Well conclusions faxexRandR is easy to install and to use on Ubuntu (18.04 LTS)- but apparently not able to detect the x display on Raspberry so better use xrandr directly which works fine.
